<?php

return [
    'invoice_aging' => [
        'Client / Debtor',
        'PO#',
        'Invoice#',
        'Purchase Date',
        'Sch#',
        'Invoice Amount',
        'Paid Date',
        'Balances',
        'Age',
        '1-30 Days',
        '31-60 Days',
        '61-90 Days',
        '91-120 Days',
        '121+ Days',
    ],
    'payment_report' => [
        'Payor/Check#',
        'Invoice#',
        'Purchased',
        'Sch#',
        'Invoice Amount',
        'Days',
        'Check Amount',
        'Payment Amount',
        'Adjust Type',
        'Adjust Amount',
        'Escrow Amount',
        'Fee Earned',
        'Taxes Held',
    ],
    'chargeback_report' => [
        'Posted',
        'Invoice#',
        'Purchased',
        'Buy#',
        'Invoice Amount',
        'Amount Paid',
        'Paid On',
        'Col#',
        'Give Back',
        'Charge Back',
        'Write Off',
        'O/S',
        'Description',
    ],
    'ineligible_report' => [
        'Invoice#',
        'Debtor',
        'Invoice Date',
        'Date Funded',
        'Due Date',
        'Invoice Amount',
        'Balance',
        'Invoice Age',
        'Days Over',
        'Amount Eligible',
        'Available For Recourse',
        'Amount Ineligible',
        'Cross Ineligible',
        'Reason',
    ],
    'purchase_summary' => [
        'Sch#',
        'Posted Date',
        'Debtor',
        'Invoice #',
        'Invoice Date',
        'Invoice Amount',
        'Due Date',
        'Advance Rate',
        'Advance Amount',
        'Fee',
    ],
    'reserve_account_detail' => [
        'Date',
        'Invoice#',
        'Type',
        'PO#',
        'Description',
        'Check',
        'Reference',
        'Debtor',
        'Buy Date',
        'Fee Days',
        'Activity Type',
        'Check Amount',
        'Applied To A/R',
        'Applied To Advanced',
        'Applied To Fee',
        'Reserve Amount',
        'Reserve Balance',
    ],
    'client_activity_statement' => [
        'Date',
        'Accounts Receivable' => [
            'Gross Purchases',
            'Gross Receipts',
            'Discounts',
            'Other',
            'Adjustments',
        ],
        'Disbursements and Charges' => [
            'Funding',
            'Cash Receipts',
            'Charges and Fees',
            'Expenses',
            'Adjustments',
        ],
        'Balances' => [
            'Accounts Receivable',
            'Funding',
            'Cash Reserve',
        ],
    ]
];
